FROM docker.io/centos:latest
MAINTAINER guozhiwen 2018-01-19
RUN yum install epel-release -y
RUN yum -y install  openssh-server net-tools gcc gcc-c++ autoconf libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel libxml2 libxml2-devel zlib zlib-devel glibc glibc-devel glib2 glib2-devel bzip2 bzip2-devel ncurses ncurses-devel curl curl-devel e2fsprogs e2fsprogs-devel krb5 krb5-devel libidn libidn-devel openssl openssl-devel libevent-devel libevent mhash mhash-devel libmcrypt-devel libmcrypt gd gd-devel pcre pcre-devel perl perl-devel ntp sysstat links make patch bc screen cmake tree gmp gmp-devel readline libxslt    libxslt-devel GeoIP-devel  lua-devel vim netstat
